package com.beetech.module.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.beetech.module.bean.AppLog;
import com.beetech.module.bean.GpsDataBean;
import com.beetech.module.bean.ModuleBuf;
import com.beetech.module.bean.QueryConfigRealtime;
import com.beetech.module.bean.ReadDataRealtime;
import com.beetech.module.bean.vt.VtSocketLog;
import com.beetech.module.code.response.ReadDataResponse;

import com.beetech.module.greendao.dao.AppLogDao;
import com.beetech.module.greendao.dao.GpsDataBeanDao;
import com.beetech.module.greendao.dao.ModuleBufDao;
import com.beetech.module.greendao.dao.QueryConfigRealtimeDao;
import com.beetech.module.greendao.dao.ReadDataRealtimeDao;
import com.beetech.module.greendao.dao.VtSocketLogDao;
import com.beetech.module.greendao.dao.ReadDataResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appLogDaoConfig;
    private final DaoConfig gpsDataBeanDaoConfig;
    private final DaoConfig moduleBufDaoConfig;
    private final DaoConfig queryConfigRealtimeDaoConfig;
    private final DaoConfig readDataRealtimeDaoConfig;
    private final DaoConfig vtSocketLogDaoConfig;
    private final DaoConfig readDataResponseDaoConfig;

    private final AppLogDao appLogDao;
    private final GpsDataBeanDao gpsDataBeanDao;
    private final ModuleBufDao moduleBufDao;
    private final QueryConfigRealtimeDao queryConfigRealtimeDao;
    private final ReadDataRealtimeDao readDataRealtimeDao;
    private final VtSocketLogDao vtSocketLogDao;
    private final ReadDataResponseDao readDataResponseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appLogDaoConfig = daoConfigMap.get(AppLogDao.class).clone();
        appLogDaoConfig.initIdentityScope(type);

        gpsDataBeanDaoConfig = daoConfigMap.get(GpsDataBeanDao.class).clone();
        gpsDataBeanDaoConfig.initIdentityScope(type);

        moduleBufDaoConfig = daoConfigMap.get(ModuleBufDao.class).clone();
        moduleBufDaoConfig.initIdentityScope(type);

        queryConfigRealtimeDaoConfig = daoConfigMap.get(QueryConfigRealtimeDao.class).clone();
        queryConfigRealtimeDaoConfig.initIdentityScope(type);

        readDataRealtimeDaoConfig = daoConfigMap.get(ReadDataRealtimeDao.class).clone();
        readDataRealtimeDaoConfig.initIdentityScope(type);

        vtSocketLogDaoConfig = daoConfigMap.get(VtSocketLogDao.class).clone();
        vtSocketLogDaoConfig.initIdentityScope(type);

        readDataResponseDaoConfig = daoConfigMap.get(ReadDataResponseDao.class).clone();
        readDataResponseDaoConfig.initIdentityScope(type);

        appLogDao = new AppLogDao(appLogDaoConfig, this);
        gpsDataBeanDao = new GpsDataBeanDao(gpsDataBeanDaoConfig, this);
        moduleBufDao = new ModuleBufDao(moduleBufDaoConfig, this);
        queryConfigRealtimeDao = new QueryConfigRealtimeDao(queryConfigRealtimeDaoConfig, this);
        readDataRealtimeDao = new ReadDataRealtimeDao(readDataRealtimeDaoConfig, this);
        vtSocketLogDao = new VtSocketLogDao(vtSocketLogDaoConfig, this);
        readDataResponseDao = new ReadDataResponseDao(readDataResponseDaoConfig, this);

        registerDao(AppLog.class, appLogDao);
        registerDao(GpsDataBean.class, gpsDataBeanDao);
        registerDao(ModuleBuf.class, moduleBufDao);
        registerDao(QueryConfigRealtime.class, queryConfigRealtimeDao);
        registerDao(ReadDataRealtime.class, readDataRealtimeDao);
        registerDao(VtSocketLog.class, vtSocketLogDao);
        registerDao(ReadDataResponse.class, readDataResponseDao);
    }
    
    public void clear() {
        appLogDaoConfig.clearIdentityScope();
        gpsDataBeanDaoConfig.clearIdentityScope();
        moduleBufDaoConfig.clearIdentityScope();
        queryConfigRealtimeDaoConfig.clearIdentityScope();
        readDataRealtimeDaoConfig.clearIdentityScope();
        vtSocketLogDaoConfig.clearIdentityScope();
        readDataResponseDaoConfig.clearIdentityScope();
    }

    public AppLogDao getAppLogDao() {
        return appLogDao;
    }

    public GpsDataBeanDao getGpsDataBeanDao() {
        return gpsDataBeanDao;
    }

    public ModuleBufDao getModuleBufDao() {
        return moduleBufDao;
    }

    public QueryConfigRealtimeDao getQueryConfigRealtimeDao() {
        return queryConfigRealtimeDao;
    }

    public ReadDataRealtimeDao getReadDataRealtimeDao() {
        return readDataRealtimeDao;
    }

    public VtSocketLogDao getVtSocketLogDao() {
        return vtSocketLogDao;
    }

    public ReadDataResponseDao getReadDataResponseDao() {
        return readDataResponseDao;
    }

}
